name: Generate Docs Index

on:
  repository_dispatch:
    types: [generate-docs-index]

permissions:
  contents: write

jobs:
  generate-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate index.html for all module roots
        run: |
          mkdir -p scripts
          cp scripts/header.html index.html

          for dir in */; do
            [[ "$dir" == ".git/" || "$dir" == ".github/" || "$dir" == "scripts/" ]] && continue
            name=$(basename "$dir")
            echo "        <li><a href=\"./$name/\">$name</a></li>" >> index.html
          done

          sed "s/DATE_PLACEHOLDER/$(date -u)/" scripts/footer.html >> index.html

          for module in */; do
            [[ "$module" == ".git/" || "$module" == ".github/" || "$module" == "scripts/" ]] && continue

            module_name=$(basename "$module")
            skip_dirs=("images" "scripts" "styles" "ui-kit")
            skip_dirs+=("$module_name")

            has_subdir=false
            for subdir in "$module"*/; do
              name=$(basename "$subdir")
              if [[ " ${skip_dirs[*]} " == *" $name "* ]]; then
                continue
              fi
              has_subdir=true
              break
            done

            if [ "$has_subdir" = true ]; then
              module_index="$module/index.html"
              cp scripts/header.html "$module_index"

              for subdir in "$module"*/; do
                name=$(basename "$subdir")
                if [[ " ${skip_dirs[*]} " == *" $name "* ]]; then
                  continue
                fi
                echo "        <li><a href=\"./$name/\">$name</a></li>" >> "$module_index"
              done

              sed "s/DATE_PLACEHOLDER/$(date -u)/" scripts/footer.html >> "$module_index"
            else
              echo "Skipping $module (no submodules found, will not overwrite existing index.html)"
            fi

      - name: Commit and push index.html
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.html
          git commit -m "chore: auto-generate docs index ($(date +%s))" || echo "No changes to commit"
          git push

      - name: Wait a few seconds for GitHub to update refs
        run: sleep 10

      - name: Trigger deploy manually
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: deploy
