name: Auto Merge and Publish Docs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge-and-publish:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.user.login != 'ririf4' &&
      startsWith(github.head_ref, 'docs-')

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Auto-merge the PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: "squash"
            })

  deploy-pages:
    needs: auto-merge-and-publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
