name: Auto Merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge-and-publish:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.user.login != 'ririf4' &&
      startsWith(github.head_ref, 'docs-')

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Auto-merge the PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: "squash"
            })