name: Build and PR Dokka to docs repo

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate Dokka HTML
        run: ./gradlew dokkaHtml

      - name: Create doc push repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          mkdir pushrepo
          cd pushrepo
          git init
          git remote add origin https://github.com/ririf4/docs.git
          git fetch origin main
          git checkout -b docs-${{ github.repository }}

      - name: Copy docs to repo
        run: |
          cp -r build/dokka/html ./pushrepo/${{ github.event.repository.name }}

      - name: Commit and push
        run: |
          cd pushrepo
          git add .
          git commit -m "docs: update for ${{ github.repository }}"
          git push origin docs-${{ github.repository }}

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: update for ${{ github.repository }}"
          title: "Update docs for ${{ github.repository }}"
          body: "This PR updates the Dokka docs for ${{ github.repository }}"
          base: main
          branch: docs-${{ github.repository }}
          repository: RiriFa/docs
